---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skopeo-copy
  labels:
    app.kubernetes.io/version: 0.0.1
spec:
  description: | 
    Skopeo is a command line tool for working with remote image registries. 
    The copy command will take care of copying the image from internal.registry 
    to production.registry. If your production registry requires credentials to 
    login in order to push the image, skopeo can handle that as well.
  params:
    - name: SOURCE_REGISTRY
      type: string
      description: |
        It represents the Source Registry, for eg - docker.io, quay.io, 
        registry.fedoraproject.org, etc.
    - name: SOURCE_IMAGE
      type: string
      description: |
        It represents the particular Image in the Source Registry we want to copy.
    - name: SOURCE_TAG
      type: string
      description: |
        It represents the tag version of the Source Image. By default it is latest.
    - name: DESTINATION_REGISTRY
      type: string
      description: |
        It represents the Destination Registry, for eg - docker.io, quay.io, 
        registry.fedoraproject.org, etc.
    - name: DESTINATION_IMAGE
      type: string
      description: |
        It represents the particular Image in the Source Registry we want to copy.
    - name: DESTINATION_TAG
      type: string
      description: |
        It represents the tag version of the Source Image. By default it is latest.
    - name: TLS_VERIFY
      type: string
      default: "true"
      description: |
        Sets the global `http.tlsVerify` value, `false` is not advised unless
        you trust the remote repository.
  results:
    - name: SOURCE_DIGEST
      type: string
      description: Source Image Digest
    - name: DESTINATION_DIGEST
      type: string
      description: Destination Image Digest
  steps:
    - name: copy
      image: quay.io/skopeo/stable
      imagePullPolicy: Always
      command: ["skopeo"]
      args:
      - "copy"
      - "--tls-verify=$(params.TLS_VERIFY)"
      - "docker://$(params.SOURCE_REGISTRY)/$(params.SOURCE_IMAGE):$(params.SOURCE_TAG)"
      - "docker://$(params.DESTINATION_REGISTRY)/$(params.DESTINATION_IMAGE):$(params.DESTINATION_TAG)"
      env:
      - name: REGISTRY_AUTH_FILE
        value: /root/.docker/config.json
    - name: store-digest
      image: quay.io/skopeo/stable
      script: |
        SOURCE_DIGEST=$(skopeo inspect --tls-verify=$(params.TLS_VERIFY) --format='{{.Digest}}' docker://$(params.SOURCE_REGISTRY)/$(params.SOURCE_IMAGE):$(params.SOURCE_TAG)) 
        DESTINATION_DIGEST=$(skopeo inspect --tls-verify=$(params.TLS_VERIFY) --format='{{.Digest}}' docker://$(params.DESTINATION_REGISTRY)/$(params.DESTINATION_IMAGE):$(params.DESTINATION_TAG)) 
        echo $SOURCE_DIGEST > $(results.SOURCE_DIGEST.path)
        echo $DESTINATION_DIGEST > $(results.DESTINATION_DIGEST.path)
      env:
      - name: REGISTRY_AUTH_FILE
        value: /root/.docker/config.json